name: Pytest

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Conda environment cache
        id: restore-conda-environment-cache
        uses: actions/cache/restore@v3
        with:
          path: ~/.conda/envs/naas-python
          key: conda-environment-${{ hashFiles('.github/environment.yaml') }}

      - name: Set up Conda
        if: steps.restore-conda-environment-cache.outputs.cache-hit != 'true'
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          channel-priority: strict
          python-version: 3.8
          activate-environment: naas-python
          environment-file: ./.github/environment.yaml
          use-only-tar-bz2: true

      - shell: bash -el {0}
        run: |
          conda info
          printenv | sort

      - name: Install main package
        run: |
          pip install -e .[dev]

      - shell: bash -el {0}
        run: |
          pytest tests

      - name: Save Conda environment cache
        if: steps.restore-conda-environment-cache.outputs.cache-hit != 'true'
        id: save-conda-environment-cache
        uses: actions/cache/save@v3
        with:
          path: ~/.conda/envs/naas-python
          key: conda-environment-${{ hashFiles('.github/environment.yaml') }}
