name: Pytest

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: condaforge/miniforge3:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packate dependencies
        run: |
          pip install pytest pydantic

      - name: Install main package
        run: |
          conda activate naas-python
          pip install -e .[dev]

      - name: pytest
        run: |
          conda activate naas-python
          pytest tests

