name: Pytest

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true
          environment-file: ./.github/environment.yaml

      - shell: bash -el {0}
        run: |
          conda info
          printenv | sort

      - name: Install main package
        run: |
          conda activate naas-python
          pip install -e .[dev]

      - shell: bash -el {0}
        run: |
          conda activate naas-python
          pytest tests

